//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeverNotes.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupConnection
    {
        public int GroupConnectionID { get; set; }
        public int NoteID { get; set; }
        public int NoteGroupID { get; set; }
    
        public virtual Note Note { get; set; }
        public virtual NoteGroup NoteGroup { get; set; }
    }
}
