//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeverNotes.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForeverNotesEntities : DbContext
    {
        public ForeverNotesEntities()
            : base("name=ForeverNotesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GroupConnection> GroupConnection { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<NoteGroup> NoteGroup { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<TagConnection> TagConnection { get; set; }
    }
}
