//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeverNotes.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoGroupConnection
    {
        public int ToDoGroupConnectionID { get; set; }
        public int ToDo_ToDoID { get; set; }
        public int ToDoGroup_ToDoGroupID { get; set; }
    
        public virtual ToDo ToDo { get; set; }
        public virtual ToDoGroup ToDoGroup { get; set; }
    }
}
